package com.artstudio3d.creativeflow.models

data class EmpresaModel(val id: Int,
                        val codigoEmpresa: String,
                        val nombreComercial: String?,
                        val nombreFiscal: String,
                        val formaJuridica: String,
                        val direccion: String,
                        val cp: String?,
                        val poblacion: String?,
                        val provincia: String?,
                        val pais: String,
                        val logoRuta: String?,
                        val cifSiren: String,
                        val siret: String?,
                        val apeNaf: String?,
                        val rcs: String?,
                        val ciudadRcs: String?,
                        val inscripcion: String?,
                        val telefono1: String?,
                        val telefono2: String?,
                        val movil: String?,
                        val email: String?,
                        val web: String?,
                        val enlaceWeb: Boolean = false,
                        val gestionInternacional: Boolean = false,
                        val fechaAlta: String?, // Guardado como String para simplificar el manejo de fechas SQL
                        val diaCierreEjercicio: Int = 31,
                        val mesCierreEjercicio: Int = 12,
                        val autocodificarNuevosArticulos: Boolean = false,
                        val tamanoCodigoArticulo: Int = 13,
                        val irpf: Boolean = false,
                        val porcentajeIrpf: Double = 0.0,
                        val idTarifa: Int = 0,
                        val margenArticulos: Double = 0.0,
                        val margenMinimoArticulo: Double = 0.0,
                        val actualizarDivisas: Boolean = false,
                        val idDivisa: Int?,
                        val digitosFactura: Int = 6,
                        val serieFactura: String = "F-",
                        val decimalesEnCalculos: Int = 2,
                        val decimalesPrecios: Int = 2,
                        val comentariosAlbaran: String?,
                        val comentariosContratoServicio: String?,
                        val comentariosFacturas: String?,
                        val horariosLunes: String?,
                        val horariosMartes: String?,
                        val horariosMiercoles: String?,
                        val horariosJueves: String?,
                        val horariosViernes: String?,
                        val horariosSabado: String?,
                        val horariosDomingo: String?,
    // Campos Google
                        val googleId: String?,
                        val googleEmail: String?,
                        val googleAccessToken: String?,
                        val googleRefreshToken: String?,
                        val googleTokenExpiresAt: String?,
                        val googleCalendarId: String?,
                        val googleLastSyncToken: String?,
    // Cuentas Contables
                        val cuentaClientes: String?,
                        val cuentaProveedores: String?,
                        val cuentaVentaMercaderias: String?,
                        val cuentaVentaServicios: String?,
                        val cuentaIvaSoportadoN: String?,
                        val cuentaIvaSoportadoR: String?,
                        val cuentaIvaSoportadoSr: String?,
                        val cuentaIvaSoportadoE: String?,
                        val cuentaIvaSoportadoReN: String?,
                        val cuentaIvaSoportadoReR: String?,
                        val cuentaIvaSoportadoReSr: String?,
                        val cuentaIvaSoportadoReE: String?,
                        val cuentaIvaRepercutidoN: String?,
                        val cuentaIvaRepercutidoR: String?,
                        val cuentaIvaRepercutidoSr: String?,
                        val cuentaIvaRepercutidoE: String?,
                        val cuentaIvaRepercutidoReN: String?,
                        val cuentaIvaRepercutidoReR: String?,
                        val cuentaIvaRepercutidoReSr: String?,
                        val cuentaIvaRepercutidoReE: String?,
    // Conexiones DB
                        val motorDb: String = "MariaDB",
                        val archivoSqlite: String?,
                        val mariadbHost: String?,
                        val mariadbPort: String?,
                        val mariadbName: String?,
                        val mariadbUser: String?,
                        val mariadbPassword: String?,
                        val postgreHost: String?,
                        val postgreName: String?,
                        val postgreUser: String?,
                        val postgrePort: String?,
                        val postgrePassword: String?
)
